---
# tasks file for envinput
- name: Creating parameter template
  template:
   src: envtmp.j2
   dest: /home/ubuntu/.random.yml
   force: yes
- name: create global varialbe file
  shell: cat /home/ubuntu/.random.yml|tr -d \"| tr 'A-Z' 'a-z' > /home/ubuntu/.globalvariables.yml
